version: '3.9'

services:

  web:
    build:
      dockerfile: ./mysite/Dockerfile
    command:
      # - "python"
      # - "manage.py"
      # - "runserver"
      # - "0.0.0.0:8000"
      - "gunicorn"
      - "--bind"
      - "0.0.0.0:8000"
      - "mysite.wsgi"
    # ports:
    #   - "8000:8000"
    expose:
      - 8000
    volumes:
      - ./mysite:/app
    env_file:
      - ./.env.prod
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - ./mysite/static:/app/static
    ports:
      - 80:80
    depends_on:
      - web
    restart: always
